# Generated by Django 3.0.7 on 2020-06-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='length',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='res',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='tu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
