# Generated by Django 3.0.7 on 2020-06-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_factory', '0002_auto_20200614_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='adress',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
