# Generated by Django 3.0.7 on 2020-07-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_factory', '0004_remove_entrymodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='notes',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='status',
            field=models.CharField(default='В работе', max_length=100),
        ),
    ]
