# Generated by Django 3.0.7 on 2020-07-15 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_factory', '0005_auto_20200702_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='contractDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 15, 16, 1, 6, 567693)),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='contractNumber',
            field=models.TextField(default='П-01', max_length=100),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='cost',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
