# Generated by Django 3.0.7 on 2020-07-16 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_factory', '0006_auto_20200715_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='contractDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 16, 16, 54, 13, 274894)),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='cost',
            field=models.FloatField(default=50000.0),
        ),
    ]
