# Generated by Django 3.0.7 on 2020-07-16 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_factory', '0007_auto_20200716_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='contractDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 16, 16, 57, 21, 272133)),
        ),
    ]
